name: Test Project
on: push
  branches: 
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name : Set up swift
        uses: swift-actions/setup-swift@v3
        with:
          swift-version "6.0"
      - name: get swift version
        run: swift --version 
      - name: run tests
        run: swift test