# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Swift

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.10","6.0"]
    runs-on: ${{ matrix.os }}
    steps: 
      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest
      - name : Setup swift
        uses: swift-actions/setup-swift@v3
        with:
          swift-version: ${{ matrix.swift }}
          skip-verify-signature: true
      - name: get swift version
        run: swift --version 
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Build
        run: swift build -Xswiftc -strict-concurrency=complete
      - name: Run tests
        run: swift test -Xswiftc -strict-concurrency=complete
